### ISSUE TITLE
Klasse für Scheibe

### ISSUE THREAD

**Issue by WillyWinkel** [mp1409/kislab#10]
hab ich die übersehen, kommt die noch?

**Comment by mp1409** [comment]
Prinzipiell ist das eine gute Idee, aber bevor wir 106dee26a2bc510913444158f0c857438516037a zu Master mergen können, sind noch ein paar Dinge zu tun:
- Da ist eine Datei ".sconsign.dblite" und "main.o" fälschlicherweise eingcheckt.
- Die Kommentare in sind teilweise nicht vorhanden (was tut "go"?), teilweise sind sie schlicht falsch (Copy & Paste).
- Du includest im Header einen Haufen Kram, der (noch) nicht benutzt wird. Bitte dran denken, dass der Programmspeicher vom Atmel nur ein paar KB groß ist, deshalb nur includen, wenn du was auch tatsächlich benutzt.
- Den Ordner Hardware würde ich für tatsächlich ansteuerbare Komponenten gedacht, die Scheibe ist ja mehr ein Modell. Daher würde ich den Kram in den (neuen) Order "model" packen.

**Comment by mp1409** [comment]
PS: "test" ist keine gute Commit-Message ;-)

**Comment by WillyWinkel** [comment]
jo war ein test, um genau zu sein war ich überrascht wie schnell mit git ein branch geöffnet/gepusht werden kann. ich machs mal sauber, bin jetzt aber erstmal fett essen

**Comment by mp1409** [comment]
Merged mit dbd1813ef93d48727d0c87896bb6020453a75d0f, Grammar-Nazi fertig mit 0ecb7ac66c8058ee7ebd5ad93aad6cdd651ef7f2.
