### ISSUE TITLE
Messwertdiagramm der Sensorwerte einer Scheibenumdrehung erstellen

### ISSUE THREAD

**Issue by WillyWinkel** [mp1409/kislab#11]
"Als Abschluss der Aufgabe sind die Sensorwerte für eine Drehung der Drehscheibe bis zum Stillstand zu erfassen und in einem sinnvollen Diagramm darzustellen."

Um die aufgabe zu beenden können wir wie folgt vorgehen:
- wir geben sensoraktivität pro zeiteinheit vom adruino aus und packen uns das in ein file
- plotten das ganze dann mit markus wunderschöner [software](https://github.com/thillux/rPlots)
- done

**Comment by mp1409** [comment]
Die Ausgabe muss auf die Serielle Konsole erfolgen, nicht in ein File. Entweder kann dann die Arduino IDE das in eine Datei speichern, oder man erledigt das z.B. per Skript. @WillyWinkel , übernimmst du diesen Part? Als Endergebnis sollte dann ein CSV herausfallen.

@HolyShitMan hat für das schematische Diagramm schon eine sehr schöne Visualisierung gefunden, dass sollten wir für die Messwerte übernehmen. Übernimmst du den Teil CSV->Grafik?

**Comment by HolyShitMan** [comment]
Hatte ich vor, ja.
Martin hat heute von einem Programm erzählt, was den Konsolenausgang direkt in eine Datei gepiped hat. Ich bekomme mal raus was die da genommen haben. Könnte ja evtl. ganz sinnvoll sein.

**Comment by mp1409** [comment]
Eventuell sowas:
http://superuser.com/q/129447

Alternativ kann ich auch mit [pyserial](https://github.com/pyserial/pyserial) was hacken.

**Comment by HolyShitMan** [comment]
Martin meinte sie hätten es mit "processing" abgefangen. Das tool ist allerdings echt gigantisch, evtl etwas overkill. Wenns also einfacher geht

**Comment by WillyWinkel** [comment]
übersehe ich was oder können wir nicht einfach ne textausgabe kopieren?

**Comment by mp1409** [comment]
Ich weiß nicht genau, was das entsprechende Fenster in der Arduino-IDE zulässt. Das Windows-Shell-Kommando von Stackoverflow von oben sollte es aber definitiv tun. Processing ist definitiv Overkill...

**Comment by mp1409** [comment]
Update:
- Seit b7a6ece0f96915145c091b50dabe9250fce9ebe7 können wir CSV-Daten auf die serielle Konsole schreiben
- Seit d5d1a8d1360770e5c343bba97d6b4ab582ad31d8 können wir CSV-Daten plotten

**Comment by HolyShitMan** [comment]
Funktioniert!
