### ISSUE TITLE
Bauen ohne Scons

### ISSUE THREAD

**Issue by WillyWinkel** [mp1409/kislab#12]
also scons ist raus?! wie kann ich noch lokal checken ob mein stuff baut?

**Comment by mp1409** [comment]
[Wiki](https://github.com/mp1409/kislab/wiki/Workflow) gelesen? Hatte das beim Entfernen vom SConstruct-File schon mal aktualisiert. Vielleicht wars nicht deutlich genug, ich habs jetzt nochmal versucht zu präzisieren...

**Comment by WillyWinkel** [comment]
aye
