### ISSUE TITLE
Shell scripte für Debian Betriebssystem

### ISSUE THREAD

**Issue by HolyShitMan** [mp1409/kislab#3]
@mp1409 In Debian Systemen liegt die Shell unter `/bin/sh` und nicht `/usr/bin/sh`
Das führt zu Komplikationen...

**Comment by mp1409** [comment]
Bitte mit 1815146febe726349eee87dafec941ecb0c384f3 nochmal testen.

**Comment by HolyShitMan** [comment]
läuft
