### ISSUE TITLE
Schematisches Diagramm der Sensorwerte einer Scheibenumdrehung erstellen

### ISSUE THREAD

**Issue by mp1409** [mp1409/kislab#7]
Schematisches Diagramm der Sensorwerte über eine Umdrehung erstellen und dem Laborbericht hinzufügen.

**Comment by WillyWinkel** [comment]
beziehst du dich auf "Als Abschluss der Aufgabe sind die Sensorwerte für eine Drehung der Drehscheibe bis zum Stillstand zu erfassen und in einem sinnvollen Diagramm darzustellen." im [moodle](https://moodle2.tu-ilmenau.de/course/view.php?id=1021)?

**Comment by mp1409** [comment]
Das sollte primär das Diagramm sein, was Simon gestern Nachmittag erwähnt hat (also mehr schematisch als Messwerte)...

**Comment by mp1409** [comment]
Für die Messwerte gibt es jetzt #11.

**Comment by mp1409** [comment]
@HolyShitMan, kannst du möglicherweise den Code zur Erzeugung des Diagramms und nicht die fertige Datei in das Repo packen? Und die Grapherzeugung mit ins Latex-Buildscript aufnehmen? Nur wenn das nicht zu aufwendig wird...

**Comment by HolyShitMan** [comment]
@WillyWinkel War gestern nur ein erster Test. Habe vorhin im Zug ein Skript erstellt. Das lade ich noch hoch.
Die Abhängigkeiten zum Plotten sind halt etwas Mist weil ich dafür Julia (http://julialang.org/) mit Gadfly und Cairo nutze. Muss ich mal schauen ob und wie ich das sinnvoll einbinden kann ;)

**Comment by mp1409** [comment]
@HolyShitMan Hat deine Skripte so erweitert, dass man auch Distro-Packages von Julia verwenden kann. Teste bitte mal bei Gelgenheit, ob das bei dir noch alles funktioniert. Kann die Datei "graph_test.pdf" dann eigentlich weg?

**Comment by HolyShitMan** [comment]
@mp1409 Die Datei kann weg.
Habe ich gesehen und geht auch alles noch. Allerdings ist das DistroPaket glaube ich nicht auf dem neusten Stand. Bei mir haben die Erweiterungen jedenfalls nicht funktioniert. Deswegen war ich auf den vorkompilierten krams umgestiegen...

**Comment by mp1409** [comment]
@HolyShitMan Datei gelöscht mit 45fcd7a9ae79fc471f55e6136016c80138a8fa8d. Du hast recht, das Paket für Trusty (und damit ja auch Mint) scheit ziemlich alt zu sein. Aber ich denke, so wie die Skripte jetzt sind geht das für beide Systeme in Ordnung.

Wenn ich das richtig verstehe ist `sensoren.jl` für die schematische Darstellung und `csv.jlx` für die Messwerte, oder?

**Comment by HolyShitMan** [comment]
@mp1409 Genau. 
- sensoren.jl ist fest konfiguriert und braucht keine Parameter. Die genaue Anpassung, dass das auch stimmt mache ich dann nächste Woche wenn ich mal ins Labor konnte.
- Ich habe csv.jlx und das build.sh skript so angepasst, dass für alle *.csv dateien  mit den Achsenbeschriftungen der ersten CSV-Zeile geplottet (Punkte mir approximierter Kurve) werden. Die PDF hat den Namen der CSF-Datei.
  Mit dem was aus b7a6ece0f96915145c091b50dabe9250fce9ebe7 heraus fällt harmoniert das zwar noch nicht ganz, müssen wir mal schauen auf welcher ebene wie die umrechnung in die Schreibengeschwindigkeit machen.

Soll ich die Umrechnung auch noch in das (bzw. vielleicht ein neues falls wir das noch brauchen :smile: ) Skript packen?!

**Comment by mp1409** [comment]
@HolyShitMan Ich hab mit 7914e15a2077f6f65c2d3a8bd2f3c46cce37a3c5 die Skripte umbenannt, damit das klarer wird.

Zur Umrechnung: Ich würde soviel wie möglich außerhalb des Arduino tun. Also schreib das ruhig erstmal in Julia, wenn du eine zündende Idee hast. Falls wir das später trotzdem auf dem Arduino brauchen, schreiben wirs dort halt nochmal in C++.
